[package]
name = "juice"
version = "0.1.0"
edition = "2024"

[dependencies]
turbo = { version = "4.0.0", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
